### PR TITLE
Test for mirroring more than one field

### PR DESCRIPTION
**Pull request by aklaing**
In response to a comment by @joaotavora on Issue #932.

### CODE REVIEW

**Comment by npostavs** [comment]
Awesome, thanks! Have you assigned copyright for Emacs? (the patch is *just* small enough to
install regardless, I'm asking to know if it should be marked as a tiny change).

**Comment by aklaing** [comment]
I'm very willing to assign the copyright.  I agree it is very small.  But if you want it formally I will sign it off.  Okay so the emacs documentation says I should have put one line into the commit message to do this but I forgot:

> If the commit is a tiny change that is exempt from copyright paperwork,
>   the commit message should contain a separate line like the following:
> 
> 	Copyright-paperwork-exempt: yes

If this github comment by me is sufficient, then that's great.  if not, should I create a new commit?  I am absolutely willing to treat it as a small change.

**Comment by aklaing** [comment]
Never mind.  Let me do it over again, with a proper commit message and including the copyright line.

**Comment by aklaing** [comment]
Nah, its not really necessary to redo it.  I assign the copyright, GPL 3.  Thanks !!!

**Comment by npostavs** [comment]
A+ for enthusiasm :)

But assigning copyright is a bit more complicated than that.

To start the copyright assignment process, fill in this [form](https://git.savannah.gnu.org/cgit/gnulib.git/tree/doc/Copyright/request-assign.future), with "Emacs" as the program name, and send it to the mentioned email address. They'll send you more instructions.

**Comment by aklaing** [comment]
I've sent the email to assign@gnu.org with the requested information.  But I expect it is going to take a very long time to process (I've done it before for sisu-mode.el).  And [this page](https://www.gnu.org/software/emacs/manual/html_node/emacs/Copyright-Assignment.html) says that emacs will accept changes of fewer than 15 lines without a formal copyright assignment, so technically if you wish to proceed, you may.  Thanks.

**Comment by npostavs** [comment]
Well, adding test code is less urgent, so I'd prefer to wait. That way, there's less chance of getting confused later when your assignment has been processed but you still have a tiny change listed in the git log (I don't personally have access to the FSF assignments list, so I somewhat rely on what a contributor's previous commit message says).

When I did the assignment, I waited about a month for it to go through, but more recently I've seen people go through it in a week, so you might not be waiting all that long.

**Comment by aklaing** [comment]
Sounds good.  I will fill the form as soon as it arrives, and keep you posted.  Thanks.

**Comment by npostavs** [comment]
Hey, any update on this? If there is some holdup, I will just go ahead and merge as a "tiny change".

**Comment by aklaing** [comment]
Sorry I forgot to get back to you.  The fully signed copyright assignment
number is 1291566.  If you wish to see the document (a pdf file), please
send me your personal email address because I don't want to post it onto
github.
Thanks,
Ambrose

**Comment by npostavs** [comment]
> If you wish to see the document (a pdf file),

No need for that, I just take your word for it. I don't think anybody would lie about it, what would be the point?

**Pull request merged**
