### PR TITLE
Push modifications to buffer-undo-list, even if unwinding

### PR DESCRIPTION
**Pull request by pestctrl**
I've written a couple of yasnippets for ledger, that involve user input through org-read-date. Something like this:

```
# -*- mode: snippet -*-
# name: Credit Card
# key: cred                                                                       
# --
`(format-time-string "%Y/%m/%d" (org-read-date nil t))` ${0:Charge to Credit Card}
    ${2:Exp}  ${1:\$100}
    Lia:CreditCard
```
However, occasionally I change my mind after expanding the yasnippet, and hit C-g. This completely ruins undo-tree, it's basically unusable. 

The patch I've proposed fixes this, though IDK if there's a more elegant way to fix this. I noticed that if the block of code that modifies the buffer-undo-list still executes after hitting C-g, everything is fine. So, I'm wrapping the whole block that is "inserting" the snippet with an unwind-protect, to ensure that the proper values still get pushed to buffer-undo-list. 

Is this good?

### CODE REVIEW

**Comment by pestctrl** [comment]
ping

**Comment by monnier** [comment]
Really?  Ping already after waiting what... not even 2 years?  Come on, give us a break!

More seriously: We should use `undo-amalgamate-change-group` instead, but in the mean time your change looks OK (it's going to do the wrong thing if we get an error before we `narrow-to-region`, but that seems much less likely than your case).

But I can't just merge your change because it has conflict with the current code.  Can you fix the conflict?

**Comment by pestctrl** [comment]
Branch has been rebased.

**Comment by monnier** [comment]
Thank you!
And sorry it took so long.

**Comment by pestctrl** [comment]
Yay!

**Pull request merged**
