### PR TITLE
Replace no-jit/nojit with eager-loading

### PR DESCRIPTION
**Pull request by maty535**
Some adjustments

### CODE REVIEW

**Comment by npostavs** [comment]
I'm confused as to why @Bost isn't making this PR, and what is that merge commit about.

Anyway, can you resolve the conflict please?

**Comment by maty535** [comment]
I have same opinion to this, as you Noam. But please help mi to merge his PR changes, probably I have no write access to your repository. I'm getting from git this errror:

This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.

**Comment by maty535** [comment]
Thank you for help. I'm going to try this.

**Comment by Bost** [comment]
@npostavs me and maty535 we collaborate a little bit. Basically I show maty535 how to contribute to open source, use github etc. If that produces too much noise for you then I'll do all the PRs by myself, when I get the FSF copyright assignment - I'm at it, it's in progress.

**Comment by npostavs** [comment]
> Basically I show maty535 how to contribute to open source, use github etc.

Ok, that's fine, I was just confused, that's all. I think this PR would be a good way to learn how to resolve conflicts in git, as the conflict should be pretty simple.

> I'll do all the PRs by myself, when I get the FSF copyright assignment - I'm at it, it's in progress.

That's good to hear. By the way, the copyright thing is not dependent on who does the PR, it's about who *writes* the code. I would still consider this one small enough to commit without assignment anyway, since it is effectively `s/no-?jit/eager-loading/`, even though the nominal line count is higher.

**Comment by Bost** [comment]
@npostavs I still haven't received any copyright assignment nor any other reply from FSF. Two days ago I pinged copyright-clerk@fsf.org, assign@gnu.org, info@fsf.org and... nothing. I guess it's pointless to send you any PRs no matter how small or big if you can't merge them to upstream anyway  :-(

**Comment by npostavs** [comment]
Well, when I sent my copyright assignment request it took 22 days before I received the initial response, so the waiting time isn't completely unprecedented. If you still haven't heard anything by next week, we can try asking on emacs-devel, probably someone there knows how to ping "louder", so to speak.

**Comment by npostavs** [comment]
@Bost Have you heard anything yet? If no, do you want to try on emacs-devel?

**Comment by Bost** [comment]
@npostavs I received the assignment about 3 days ago. And more importantly, I picked up the work again already. Although, it's not easy to find the motivation after such a break.

While at it, I noticed the ert test `basic-lazy-loading` (using `M-x ert-run-tests-interactively`) fails on the master branch. Can you confirm me this please? Otherwise I'd need a hint or two how to test my changes. (Thanx in advance)

**Comment by npostavs** [comment]
> I received the assignment about 3 days ago. And more importantly, I picked up the work again already.

That's great! :)

> Although, it's not easy to find the motivation after such a break.

I'm sorry to hear that. There hasn't been much chance to practice welcoming new contributors, so the process might be a little rough. I think you're the first person to sign for Emacs copyright specifically to be able to contribute to yasnippet since, um, me!

Would it have been better if I had asked you to submit your contributions even before finishing the assignment? I suppose I actually could have pushed them to master in the github repo, it's only the ELPA repo that has the restriction, so it would just mean I'd be unable to sync them until you finished your assignment.

> While at it, I noticed the ert test `basic-lazy-loading` (using `M-x ert-run-tests-interactively`) fails on the master branch. Can you confirm me this please? Otherwise I'd need a hint or two how to test my changes. (Thanx in advance)

I believe it should work interactively as well, but depending on what other buffers are already open it can fail. It's been something I've kind of been meaning to fix, but since it generally doesn't cause problems for users I haven't got round to it.

So from the the checked-out yasnippet repo doing `emacs -Q  -L . -l yasnippet-tests.el -f ert` (then press enter at the prompt) is the most reliable way to run the tests interactively.

**Pull request closed without merging**
