### PR TITLE
Release 0.12.0

### PR DESCRIPTION
**Pull request by npostavs**
0.12.0 should be released soon. Beginning of May perhaps.

### CODE REVIEW

**Comment by zw963** [comment]
Cool~  hope #806 could fix in this version.

**Comment by npostavs** [comment]
Yes, it's a regression from 0.11, it will definitely be fixed in 0.12.

**Comment by zw963** [comment]
Still not release 0.12 ? 

current is Jun 17. : )

**Comment by zw963** [comment]
Cool

**Comment by npostavs** [comment]
> Still not release 0.12 ?
> 
> current is Jun 17. : )

It's pushed. Only 2 months late :)

**Pull request merged**
