### PR TITLE
Yas selected text escape

### PR DESCRIPTION
**Pull request by rubikitch**

### CODE REVIEW

**Comment by npostavs** [comment]
Why only escaping for new snippets? Perhaps we should always be escaping the output of backquotes?

**Comment by npostavs** [comment]
Oh I get it, we want to escape it when writing the new snippet body, because escapes will be interpreted when the snippet is expanded.

**Comment by npostavs** [comment]
Do you have copyright assignment? (change is small enough to install regardless)

**Comment by rubikitch** [comment]
yes!

**Comment by npostavs** [comment]
Thanks, I've squashed this to `master`.

**Pull request closed without merging**
